export const LOAD_ARTICLES_INIT = "LOAD_ARTICLES_INIT";
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL';

export const SHOW_ARTICLE_INIT = 'SHOW_ARTICLE_INIT';
export const SHOW_ARTICLE_SUCCESS = 'SHOW_ARTICLE_SUCCESS';
export const SHOW_ARTICLE_FAIL = 'SHOW_ARTICLE_FAIL';

export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';

export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';


